#!/usr/bin/env bash
set -e

bazel build //cyber/...
bazel test //cyber/...
bazel build //cyber_py3/...
bazel test //cyber_py3/...
bazel build //examples/...

## TODOs
# 1) cyber_visualizer
# 2) cyber release build
# 3) Reorg tutorials and docs
# 4) ROS 1/2 Inter-Op

