#!/usr/bin/env bash

bazel build //cyber/...
bazel test //cyber/...
bazel build //cyber_py3/...
bazel test //cyber_py3/...
bazel build //examples/...

## TODOs
# 1) cyber_visualizer
# 2) release build
